### ISSUE TITLE
License file or statement

### ISSUE THREAD

**Issue by panjiesw** [ant-design/ant-design-colors#4]
Hi there,

Thank you for exposing this generator from `antd` color spec in pure JS. I'd really like to use this in my project, and noticed that it's under MIT license in `package.json`, but currently there is no license attached in this repository.

It'd be nice if you provide the MIT `LICENSE` file or statement in `README` so people would aware without peeking into `package.json` first.

Cheers!

**Comment by JLHwung** [comment]
cc @afc163
It would be great to add `LICENSE` to the project and re-publish this package, so that `LICENSE` will be in distributed npm tarball.
