### ISSUE TITLE
Cannot find module './generate'

### ISSUE THREAD

**Issue by 5argon** [ant-design/ant-design-colors#65]
The latest version 4.0.4 has the same problem as #8 again.

```
node_modules/@ant-design/colors/dist/src/index.d.ts:1:22 - error TS2307: Cannot find module './generate' or its corresponding type declarations.

1 import generate from './generate';
```

![image](https://user-images.githubusercontent.com/5653276/89320493-bb660b00-d6ab-11ea-88e4-d611ffd5cbcc.png)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design-colors/pull/64
