### ISSUE TITLE
main dependencies @ctrl/tinycolor 3.X is not support ie 11,  maybe should change ?

### ISSUE THREAD

**Issue by 405go** [ant-design/ant-design-colors#71]
[https://github.com/scttcper/tinycolor/pull/203](https://github.com/scttcper/tinycolor/pull/203)

**Comment by 405go** [comment]
I use webpack alias to reslove it like this:
'@ctrl/tinycolor': path.resolve(__dirname, '../node_modules/@ctrl/tinycolor/dist/module/public_api')

**Comment by scttcper** [comment]
es5 on main export is now supported in https://github.com/scttcper/tinycolor/releases/tag/v3.3.0
