### ISSUE TITLE
color 等单词用的是美式英语，但发现 灰色（gray） 一词用的是英式的 grey

### ISSUE THREAD

**Issue by ETRick** [ant-design/ant-design-colors#80]
这导致我长时间以为这个库里面是没有灰色的。

https://github.com/ant-design/ant-design-colors/blob/abc18fd97ecd5a45f81eef70bd250319a1736fd6/src/index.ts#L22

**Comment by afc163** [comment]
历史遗留问题：https://github.com/ant-design/ant-design-colors/issues/3#issuecomment-452158602
